export const ERROR_RECEIVE_USER = "ERROR_RECEIVE_USER";
export const REQUEST_USER = "REQUEST_USER";
export const RECEIVE_USER = "RECEIVE_USER";

export const ERROR_SIGN_IN = "ERROR_SIGN_IN";
export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const SUCCESS_SIGN_IN = "SUCCESS_SIGN_IN";

export const ERROR_SIGN_UP = "ERROR_SIGN_UP";
export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";

export const SET_SELECTED_VEHICLE_TYPE = "SET_SELECTED_VEHICLE_TYPE";
export const SET_SELECTED_DELIVERY_STATUS = "SET_SELECTED_DELIVERY_STATUS";
export const UPDATE_PAGE_NUMBER = "UPDATE_PAGE_NUMBER";
export const UPDATE_ROWS_PER_PAGE = "UPDATE_ROWS_PER_PAGE";
export const UPDATE_CURRENT_ROW_ID = "UPDATE_CURRENT_ROW_ID";
export const FETCH_CARGOS_SUCCESS = "FETCH_CARGOS_SUCCESS";
export const FETCH_CARGOS_FAILURE = "FETCH_CARGOS_FAILURE";
export const DELETE_CARGO_STATE = "DELETE_CARGO_STATE";
export const RESET_DELETE_STATE = 'RESET_DELETE_STATE';
export const CREATE_NEW_CARGO = "CREATE_NEW_CARGO";
export const SET_IS_CARGO_DATA_UPDATED = "SET_IS_CARGO_DATA_UPDATED";
export const FETCH_VEHICLE_NUMBERS = "FETCH_VEHICLE_NUMBERS";
export const FETCH_CARGO_BY_ID_SUCCESS = "FETCH_CARGO_BY_ID_SUCCESS";
export const FETCH_CARGO_BY_ID_FAILURE = "FETCH_CARGO_BY_ID_FAILURE";
