export const ENABLE_SEE_SECRET_PAGE = 'ENABLE_SEE_SECRET_PAGE';
export const ENABLE_SEE_CARGOS_LIST_PAGE = 'ENABLE_SEE_CARGOS_LIST_PAGE';
export const ENABLE_SEE_CARGO_DETAILS_PAGE = 'ENABLE_SEE_CARGO_DETAILS_PAGE';
